#ifndef __PHOTON_H__
#define __PHOTON_H__

#include "vec.h"

struct Photon
{
    vec3 position;
    vec3 direction;
    vec3 power;
};

struct Photon_Point_Cloud
{
    const std::vector<Photon>* photons;

    Photon_Point_Cloud() : photons(0)
    {
    }

    size_t kdtree_get_point_count() const
    {
        return photons ? photons->size() : 0;
    }

    double kdtree_get_pt(const size_t idx, const size_t dim) const
    {
        return (*photons)[idx].position[(int)dim];
    }

    // Generated by AI - this library is not amazingly documented, so this is a requirement for this code to function.
    template <class BBOX>
    bool kdtree_get_bbox(BBOX&) const
    {
        return false;
    }
};

#endif
